// Auto-generated from Excel — do not edit manually
const FULL_VOCAB = [
  {fa:'ـَم',tr:'Ben',ch:3,cn:'Zamirler',href:'chapter-03.html'},
  {fa:'ـی',tr:'Sen',ch:3,cn:'Zamirler',href:'chapter-03.html'},
  {fa:'ـیم',tr:'Biz',ch:3,cn:'Zamirler',href:'chapter-03.html'},
  {fa:'ـید',tr:'Siz',ch:3,cn:'Zamirler',href:'chapter-03.html'},
  {fa:'ـَند',tr:'Onlar',ch:3,cn:'Zamirler',href:'chapter-03.html'},
  {fa:'گفتم',tr:'Ben',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'گفتی',tr:'Sen',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'گفت',tr:'O',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'گفتیم',tr:'Biz',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'گفتید',tr:'Siz',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'گفتند',tr:'Onlar',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'گفته‌ام',tr:'1. Tekil (Ben)',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'گفته‌ای',tr:'2. Tekil (Sen)',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'گفته است',tr:'3. Tekil (O)',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'گفته‌ایم',tr:'1. Çoğul (Biz)',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'گفته‌اید',tr:'2. Çoğul (Siz)',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'گفته‌اند',tr:'3. Çoğul (Onlar)',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'گفته بودم',tr:'1. Tekil (Ben)',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'گفته بودی',tr:'2. Tekil (Sen)',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'گفته بود',tr:'3. Tekil (O)',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'گفته بودیم',tr:'1. Çoğul (Biz)',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'گفته بودید',tr:'2. Çoğul (Siz)',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'گفته بودند',tr:'3. Çoğul (Onlar)',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'می‌روم',tr:'Ben',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'می‌روی',tr:'Sen',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'می‌رود',tr:'O',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'می‌رویم',tr:'Biz',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'می‌روید',tr:'Siz',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'می‌روند',tr:'Onlar',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'خواهم خورد',tr:'Ben',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'خواهی خورد',tr:'Sen',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'خواهد خورد',tr:'O',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'خواهیم خورد',tr:'Biz',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'خواهید خورد',tr:'Siz',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'خواهند خورد',tr:'Onlar',ch:5,cn:'Fiil Çekimleri',href:'chapter-05.html'},
  {fa:'رفتم (Reftem)',tr:'Geçmiş',ch:6,cn:'Olumsuz & Diyalog',href:'chapter-06.html'},
  {fa:'خریدید (Harîdîd)',tr:'Geçmiş',ch:6,cn:'Olumsuz & Diyalog',href:'chapter-06.html'},
  {fa:'می‌روم (Mî-revem)',tr:'Şimdiki',ch:6,cn:'Olumsuz & Diyalog',href:'chapter-06.html'},
  {fa:'می‌خواند (Mî-hâned)',tr:'Şimdiki',ch:6,cn:'Olumsuz & Diyalog',href:'chapter-06.html'},
  {fa:'خواهم رفت',tr:'Gelecek*',ch:6,cn:'Olumsuz & Diyalog',href:'chapter-06.html'},
  {fa:'آیا رفتی؟',tr:'Gittin mi?',ch:6,cn:'Olumsuz & Diyalog',href:'chapter-06.html'},
  {fa:'آیا کتاب می‌خواند؟',tr:'Kitap okuyor mu?',ch:6,cn:'Olumsuz & Diyalog',href:'chapter-06.html'},
  {fa:'آیا خواهند آمد؟',tr:'Gelecekler mi?',ch:6,cn:'Olumsuz & Diyalog',href:'chapter-06.html'},
  {fa:'کی / چه کسی',tr:'Kim?',ch:6,cn:'Olumsuz & Diyalog',href:'chapter-06.html'},
  {fa:'چه / چی',tr:'Ne?',ch:6,cn:'Olumsuz & Diyalog',href:'chapter-06.html'},
  {fa:'کجا',tr:'Nerede?',ch:6,cn:'Olumsuz & Diyalog',href:'chapter-06.html'},
  {fa:'چطور / چگونه',tr:'Nasıl?',ch:6,cn:'Olumsuz & Diyalog',href:'chapter-06.html'},
  {fa:'کی',tr:'Ne zaman?',ch:6,cn:'Olumsuz & Diyalog',href:'chapter-06.html'},
  {fa:'کردن / انجام دادن',tr:'Yapmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'رفتن',tr:'Gitmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'آمدن',tr:'Gelmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'دیدن',tr:'Görmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'گرفتن',tr:'Almak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'دادن',tr:'Vermek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'نشستن',tr:'Oturmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'بلند شدن',tr:'Kalkmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'گپ زدن',tr:'Konuşmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'گفتن',tr:'Söylemek / Demek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'شنیدن',tr:'Duymak / İşitmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'خوردن',tr:'Yemek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'نوشیدن',tr:'İçmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'خوابیدن',tr:'Uyumak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'بیدار شدن',tr:'Uyanmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'کار کردن',tr:'Çalışmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'پیدا کردن',tr:'Bulmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'دویدن',tr:'Koşmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'قدم زدن',tr:'Yürümek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'دراز کشیدن',tr:'Uzanmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'خیز زدن',tr:'Atlamak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'سوار شدن',tr:'Binmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'پایین شدن',tr:'İnmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'پرواز کردن',tr:'Uçmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'ایستادن',tr:'Durmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'حرکت کردن',tr:'Hareket Etmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'زدن',tr:'Vurmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'انداختن',tr:'Atmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'گرفتن',tr:'Tutmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'فهمیدن',tr:'Anlamak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'فکر کردن',tr:'Düşünmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'یاد کردن',tr:'Hatırlamak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'فراموش کردن',tr:'Unutmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'ترسیدن',tr:'Korkmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'ترساندن',tr:'Korkutmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'خوشحال شدن',tr:'Sevinmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'گریه کردن',tr:'Ağlamak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'خندیدن',tr:'Gülmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'حدس زدن',tr:'Tahmin Etmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'تحمل کردن',tr:'Tahammül Etmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'گفتن',tr:'Söylemek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'پرسیدن',tr:'Sormak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'جواب دادن',tr:'Cevap Vermek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'ملاقات کردن',tr:'Görüşmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'جستجو کردن',tr:'Aramak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'صدا کردن',tr:'Çağırmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'تبریک گفتن',tr:'Tebrik Etmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'توهین کردن',tr:'Hakaret Etmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'دفاع کردن',tr:'Savunmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'فروختن',tr:'Satmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'خریدن',tr:'Satın Almak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'پرداختن',tr:'Ödemek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'قرض دادن',tr:'Borç Vermek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'مصرف کردن',tr:'Harcama Yapmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'پیشنهاد کردن',tr:'Teklif Etmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'تصمیم گرفتن',tr:'Karar Vermek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'اجازه دادن',tr:'İzin Vermek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'باطل کردن',tr:'İptal Etmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'امضا کردن',tr:'İmzalamak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'ساختن',tr:'Yapmak / İnşa Etmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'جور کردن',tr:'Tamir Etmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'بریدن',tr:'Kesmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'سوراخ کردن',tr:'Delmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'کندن',tr:'Kazmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'کاشتن',tr:'Dikmek (ekmek)',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'دوختن',tr:'Dikmek (giysi)',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'چسپاندن',tr:'Yapıştırmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'رنگ کردن',tr:'Boyamak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'شستن',tr:'Yıkamak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'پاک کردن',tr:'Temizlemek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'گرم کردن',tr:'Isıtmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'سرد کردن',tr:'Soğutmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'پخته کردن',tr:'Pişirmek',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'جوش دادن',tr:'Kaynatmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'خشک کردن',tr:'Kurutmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'تر کردن',tr:'Islatmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'سیر شدن',tr:'Doymak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'گشنه شدن',tr:'Acıkmak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'تشنه شدن',tr:'Susamak',ch:7,cn:'50 Temel Fiil',href:'chapter-07.html'},
  {fa:'عرق کردن',tr:'Terlemek',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'بودن',tr:'Olmak',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'کردن',tr:'Yapmak',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'بلند شدن - برخیستن',tr:'Kalkmak',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'استراحت کردن',tr:'Dinlenmek',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'شنیدن',tr:'Duymak',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'نگاه کردن',tr:'Bakmak',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'دانستن',tr:'Bilmek',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'خواستن',tr:'İstemek',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'شروع کردن',tr:'Başlamak',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'تمام کردن',tr:'Bitirmek',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'انتظار کردن',tr:'Beklemek',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'به‌دست آوردن',tr:'Kazanmak',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'دوست داشتن',tr:'Sevmek',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'نخواستن',tr:'İstememek',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'ناراحت شدن',tr:'Üzülmek',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'باز کردن',tr:'Açmak',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'بسته کردن',tr:'Kapatmak',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'بردن',tr:'Taşımak',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'برگشتن',tr:'Geri Dönmek',ch:8,cn:'Kategorili Fiiller',href:'chapter-08.html'},
  {fa:'من',tr:'Ben',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'تو',tr:'Sen',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'او',tr:'O',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'ما',tr:'Biz',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'شما',tr:'Siz',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'آنها',tr:'Onlar',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'من امدم',tr:'Ben geldim',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'تو رفتی',tr:'Sen gittin',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'او مریض است',tr:'O hasta',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'هست',tr:'Var',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'نیست',tr:'Yok',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'بلی- بله',tr:'Evet',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'نخیر- نه',tr:'Hayır',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'است',tr:'-dir / -dır',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'این',tr:'Bu',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'آن',tr:'Şu / O',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'این‌ها',tr:'Bunlar',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'آن‌ها',tr:'Onlar',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'این قلم',tr:'Bu kalem',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'او خانه',tr:'O ev',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'اینها کتاب اند',tr:'Bunlar kitap',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'چی',tr:'Ne',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'چی را',tr:'Ne-yi',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'کی',tr:'Kim',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'چرا',tr:'Niye / Neden',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'کسی- کس',tr:'Kimse',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'خودم',tr:'Kendim',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'خودت',tr:'Kendin',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'خودش',tr:'Kendisi',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'خودمان',tr:'Kendimiz',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'خودتان',tr:'Kendiniz',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'خودشان',tr:'Kendileri',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'این‌قدر',tr:'Bu kadar',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'آن‌قدر',tr:'O kadar',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'این‌گونه',tr:'Bu şekilde',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'آن‌چنان',tr:'O şekilde',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'این‌طور',tr:'Bu tavır',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'و',tr:'Ve',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'اما / ولی',tr:'Ama',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'یا',tr:'Veya',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'اگر',tr:'Eğer',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'زیرا',tr:'Çünkü / Zira',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'مگر',tr:'Meğer',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'تا',tr:'Ta / kadar',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'مثل / مانند',tr:'Gibi',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'فلذا',tr:'Bu yüzden',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'چرا؟',tr:'Neden? (Niçin?)',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'در کجا؟ / کجا؟',tr:'Nerede?',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'در بلخ',tr:'Belh’te',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'در حیات / در زندگی',tr:'Hayatta',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'در افغانستان',tr:'Afganistan’da',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'در مدرسه',tr:'Medresede',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'در فضا',tr:'Uzayda',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'در کورس است',tr:'Yurttadır (Kurstadır)',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'روی میز',tr:'Masa üstü',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'روی دیوار',tr:'Duvar üstü',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'بر شما',tr:'Sizin üzerinize',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'برمیز',tr:'Masa üstü',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'بر دبوار',tr:'Duvar üstü',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'با چه؟ / با چی؟',tr:'Ne ile?',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'با آنها / با ایشان',tr:'Onlarla',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'با علی',tr:'Ali ile',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'با جماعت',tr:'Cemaatle',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'با دانشجویان / با شاگردان',tr:'Talebelerle',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'با شما',tr:'Sizinle',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'به شما',tr:'Size',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'به افغانستان',tr:'Afganistan’a',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'به علی',tr:'Ali’ye',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'به خانه رفتند',tr:'Eve gittiler',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'به مدرسه نیامد',tr:'Medreseye gelmedi',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'برای چه؟ / چرا؟',tr:'Ne için?',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'برای من',tr:'Benim için',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'برای اینها',tr:'Bunlar için',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'درس بخوانید',tr:'Ders çalışın',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'بیایید',tr:'Gelin',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'بروید',tr:'Gidin',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'کمک کرده‌اند',tr:'Yardım etmişler',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'صلح نکرده‌اند',tr:'Barış yapmamışlar',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'مشورت نکرده‌اند',tr:'Danışmamışlar',ch:9,cn:'Aşamalı Konuşma',href:'chapter-09.html'},
  {fa:'بفرمایید',tr:'Buyurun',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'مرحبا',tr:'Merhaba',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'خوش آمدید',tr:'Hoş geldiniz',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'خوش باشید',tr:'Hoş bulduk',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'چطور هستید؟',tr:'Nasılsınız?',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'خوب هستم',tr:'İyiyim',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'شما چطور هستید؟',tr:'Siz nasılsınız?',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'نام شما چیست؟',tr:'Adınız nedir?',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'تخلص تان چیست؟',tr:'Soyadınız nedir?',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'نام من احمد است',tr:'İsmim Ahmet',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'نام پدر شما چیست؟',tr:'Babanızın ismi ne?',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'وظیفه شما چیست؟',tr:'Ne işle meşgulsünüz?',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'من معلم هستم',tr:'Ben öğretmenim',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'من موتروان هستم',tr:'Ben şoförüm',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'شاگرد هستم',tr:'Öğrenciyim',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'در کدام مکتب شاگرد هستید؟',tr:'Hangi okulda öğrencisiniz?',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'پح',tr:'Felah okulunda',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'صنف چند هستید؟',tr:'Kaçıncı sınıfsınız?',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'چند ساله هستید؟',tr:'Kaç yaşındasınız?',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'من بیست ساله هستم',tr:'Yirmi yaşındayım',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'ساعت چند است؟',tr:'Saat kaç?',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'ساعت چهار است',tr:'Saat dört',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'چی وقت به مکتب می‌روید؟',tr:'Okula ne zaman gidiyorsunuz?',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'زبان اصلی شما چیست؟',tr:'Ana diliniz nedir?',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'دین شما چیست؟',tr:'Dininiz nedir?',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'دین من اسلام است',tr:'Dinim İslam’dır',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'مذهب عملی شما چیست؟',tr:'Amelde mezhebiniz nedir?',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'حنفی هستم',tr:'Hanefiyim',ch:10,cn:'Tanışma',href:'chapter-10.html'},
  {fa:'سلام',tr:'Merhaba',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'حال شما چطور است؟',tr:'Nasılsınız?',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'من خوبم، تشکر',tr:'İyiyim, teşekkürler',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'نام من احمد است',tr:'Benim adım Ahmet',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'شما اهل کجا هستید؟',tr:'Nerelisiniz?',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'من از ترکیه هستم',tr:'Ben Türkiye’denim',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'آیا این راه به بلخ می‌رود؟',tr:'Bu yol Belh’e gider mi?',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'لطفاً مرا به اینجا ببرید',tr:'Lütfen buraya götürün',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'قیمت چقدر است؟',tr:'Ne kadar ücret?',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'اینجا کجاست؟',tr:'Burası neresi?',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'می‌توانم غذا بخورم؟',tr:'Yemek yiyebilir miyim?',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'می‌توانم آب بگیرم؟',tr:'Su alabilir miyim?',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'این چقدر است؟',tr:'Bu ne kadar?',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'لطفاً این را به من بدهید',tr:'Lütfen bana bunu verin',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'آیا اتاق موجود است؟',tr:'Oda var mı?',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'می‌خواهم یک شب بمانم',tr:'Bir gece kalmak istiyorum',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'قیمت چقدر است؟',tr:'Fiyat ne kadar?',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'می‌توانم کلیدم را بگیرم؟',tr:'Anahtarımı alabilir miyim?',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'می‌توانید کمک کنید؟',tr:'Yardım edebilir misiniz?',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'باید به دکتر بروم',tr:'Doktora gitmem gerekiyor',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'پلیس کجاست؟',tr:'Polis nerede?',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'می‌توانم تلفن کنم؟',tr:'Telefon edebilir miyim?',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'افغانستان خیلی زیباست',tr:'Afghanistan çok güzel',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'چه چیزی را اینجا پیشنهاد می‌کنید؟',tr:'Burada ne önerirsiniz?',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'فرهنگ شما خیلی جالب است',tr:'Kültürünüz çok ilginç',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'تشکر',tr:'Teşekkür ederim',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'خواهش می‌کنم',tr:'Rica ederim',ch:11,cn:'Afganistan',href:'chapter-11.html'},
  {fa:'یک',tr:'Bir',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'دو',tr:'İki',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'سه',tr:'Üç',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'چهار',tr:'Dört',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'پنج',tr:'Beş',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'شش',tr:'Altı',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'هفت',tr:'Yedi',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'هشت',tr:'Sekiz',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'نه',tr:'Dokuz',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'ده',tr:'On',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'یازده',tr:'On Bir',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'دوازده',tr:'On İki',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'سیزده',tr:'On Üç',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'چهارده',tr:'On Dört',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'پانزده',tr:'On Beş',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'شانزده',tr:'On Altı',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'بیست',tr:'Yirmi',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'سی',tr:'Otuz',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'چهل',tr:'Kırk',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'پنجاه',tr:'Elli',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'شصت',tr:'Altmış',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'هفتاد',tr:'Yetmiş',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'هشتاد',tr:'Seksen',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'نود',tr:'Doksan',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'صد',tr:'Yüz',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'هزار',tr:'Bin',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'میلیون',tr:'Milyon',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'میلیارد',tr:'Milyar',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'اولین / نخستین',tr:'Birinci',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'دومین',tr:'İkinci',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'سومین',tr:'Üçüncü',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'چهارمین',tr:'Dördüncü',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'پنجمین',tr:'Beşinci',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'ششمین',tr:'Altıncı',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'هفتمین',tr:'Yedinci',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'هشتمین',tr:'Sekizinci',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'نهمین',tr:'Dokuzuncu',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'دهمین',tr:'Onuncu',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'بیستمین',tr:'Yirminci',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'سی‌امین',tr:'Otuzuncu',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'چهلمین',tr:'Kırkıncı',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'پنجاهمین',tr:'Ellinci',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'شصتمین',tr:'Altmışıncı',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'هفتادمین',tr:'Yetmişinci',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'هشتادمین',tr:'Sekseninci',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'نودمین',tr:'Doksanıncı',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'صدمین',tr:'Yüzüncü',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'هزارمین',tr:'Binci',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'جمع / مثبت',tr:'Artı',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'منفی',tr:'Eksi',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'ضرب',tr:'Çarpı',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'تقسیم',tr:'Bölü',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'مساوی',tr:'Eşit',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'اعشاری, عشره',tr:'Virgül (Ondalık)',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'باقی',tr:'Kalan',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'فیصد',tr:'Yüzde',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'صد فیصد',tr:'Yüzde Yüz',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'چند فیصد',tr:'Yüzde Kaç',ch:12,cn:'Sayılar',href:'chapter-12.html'},
  {fa:'سفید',tr:'Beyaz',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'سیاه',tr:'Siyah',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'سرخ',tr:'Kırmızı',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'آبی',tr:'Mavi',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'سبز',tr:'Yeşil',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'زرد',tr:'Sarı',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'خاکستری',tr:'Gri',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'قهوه‌ای',tr:'Kahverengi',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'سرمه‌ای',tr:'Lacivert',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'نارنجی',tr:'Turuncu',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'بنفش',tr:'Mor',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'صورتی',tr:'Pembe',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'جگری',tr:'Bordo',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'سبز روشن',tr:'Açık Yeşil',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'سبز تیره',tr:'Koyu Yeşil',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'آبی روشن',tr:'Açık Mavi',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'آبی تیره',tr:'Koyu Mavi',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'نقره‌ای',tr:'Gümüş Rengi',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'طلایی',tr:'Altın Sarısı',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'کرمی',tr:'Krem',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'شتری',tr:'Deve Tüyü (Camel)',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'خاکی',tr:'Haki',ch:13,cn:'Renkler',href:'chapter-13.html'},
  {fa:'شنبه',tr:'Cumartesi',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'یکشنبه',tr:'Pazar',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'دوشنبه',tr:'Pazartesi',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'سه‌شنبه',tr:'Salı',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'چهارشنبه',tr:'Çarşamba',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'پنجشنبه',tr:'Perşembe',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'جمعه',tr:'Cuma',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'هفته',tr:'Hafta',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'ماه',tr:'Ay',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'روز',tr:'Gün',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'سال',tr:'Yıl / Sene',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'قرن',tr:'Asır / Yüzyıl',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'شام',tr:'Akşam',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'شب',tr:'Gece',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'ساعت',tr:'Saat',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'دقیقه',tr:'Dakika',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'ثانیه',tr:'Saniye',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'ثالثه',tr:'Salise',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'بیست و چهار ساعت',tr:'24 Saat',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'پیش از ظهر',tr:'Öğleden Önce',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'بعد از ظهر',tr:'Öğleden Sonra',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'فصل',tr:'Mevsim',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'بهار',tr:'İlkbahar / Bahar',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'تابستان',tr:'Yaz',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'خزان',tr:'Sonbahar',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'زمستان',tr:'Kış',ch:14,cn:'Günler & Zaman',href:'chapter-14.html'},
  {fa:'شرق',tr:'Doğu',ch:15,cn:'Yönler',href:'chapter-15.html'},
  {fa:'غرب',tr:'Batı',ch:15,cn:'Yönler',href:'chapter-15.html'},
  {fa:'شمال',tr:'Kuzey',ch:15,cn:'Yönler',href:'chapter-15.html'},
  {fa:'جنوب',tr:'Güney',ch:15,cn:'Yönler',href:'chapter-15.html'},
  {fa:'شمال‌شرق',tr:'Kuzeydoğu',ch:15,cn:'Yönler',href:'chapter-15.html'},
  {fa:'شمال‌غرب',tr:'Kuzeybatı',ch:15,cn:'Yönler',href:'chapter-15.html'},
  {fa:'جنوب‌شرق',tr:'Güneydoğu',ch:15,cn:'Yönler',href:'chapter-15.html'},
  {fa:'جنوب‌غرب',tr:'Güneybatı',ch:15,cn:'Yönler',href:'chapter-15.html'},
  {fa:'بالا',tr:'Yukarı',ch:15,cn:'Yönler',href:'chapter-15.html'},
  {fa:'پایین',tr:'Aşağı',ch:15,cn:'Yönler',href:'chapter-15.html'},
  {fa:'بغل',tr:'Yan',ch:15,cn:'Yönler',href:'chapter-15.html'},
  {fa:'پیش',tr:'Ön',ch:15,cn:'Yönler',href:'chapter-15.html'},
  {fa:'داخل',tr:'İç',ch:15,cn:'Yönler',href:'chapter-15.html'},
  {fa:'خارج / بیرون',tr:'Dış',ch:15,cn:'Yönler',href:'chapter-15.html'},
  {fa:'نقشه',tr:'Harita',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'قاره',tr:'Kıta',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'اوقیانوس',tr:'Okyanus',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'بحر',tr:'Deniz',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'بحر هند',tr:'Hint Okyanusu',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'بحر اتلانتیک',tr:'Atlantik Denizi',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'جزیره',tr:'Ada',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'ساحل',tr:'Sahil',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'خلیج',tr:'Haliç',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'موج',tr:'Dalga',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'دریا',tr:'Nehir',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'نهر',tr:'Dere',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'آبشار',tr:'Şelale',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'وادی',tr:'Vadi',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'چشمه',tr:'Pınar',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'بند آب',tr:'Baraj',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'خندق',tr:'Hendek',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'کوه',tr:'Dağ',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'تپه',tr:'Tepe',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'دشت',tr:'Ova',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'جنگل',tr:'Orman',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'صحرا',tr:'Çöl',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'خاک',tr:'Toprak',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'گل / لای',tr:'Çamur',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'صخره',tr:'Kayalık',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'سبزه',tr:'Yeşillik',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'سرحد- مرز',tr:'Sınır',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'خط استوا',tr:'Ekvator',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'قطب',tr:'Kutup',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'آفتاب‌گرفتگی',tr:'Güneş Tutulması',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'ماه‌گرفتگی',tr:'Ay Tutulması',ch:16,cn:'Coğrafya',href:'chapter-16.html'},
  {fa:'آفتاب / خورشید',tr:'Güneş',ch:17,cn:'Gökyüzü',href:'chapter-17.html'},
  {fa:'ماه- مهتاب',tr:'Ay',ch:17,cn:'Gökyüzü',href:'chapter-17.html'},
  {fa:'ستاره',tr:'Yıldız',ch:17,cn:'Gökyüzü',href:'chapter-17.html'},
  {fa:'سیاره',tr:'Gezegen',ch:17,cn:'Gökyüzü',href:'chapter-17.html'},
  {fa:'فضا- آسمان',tr:'Gök / Uzay',ch:17,cn:'Gökyüzü',href:'chapter-17.html'},
  {fa:'زمین',tr:'Yer / Dünya',ch:17,cn:'Gökyüzü',href:'chapter-17.html'},
  {fa:'وضعیت هوا',tr:'Hava Durumu',ch:17,cn:'Gökyüzü',href:'chapter-17.html'},
  {fa:'باران',tr:'Yağmur',ch:17,cn:'Gökyüzü',href:'chapter-17.html'},
  {fa:'برف',tr:'Kar',ch:17,cn:'Gökyüzü',href:'chapter-17.html'},
  {fa:'ژاله',tr:'Dolu Yağışı',ch:17,cn:'Gökyüzü',href:'chapter-17.html'},
  {fa:'بادی',tr:'Rüzgârlı',ch:17,cn:'Gökyüzü',href:'chapter-17.html'},
  {fa:'مه',tr:'Sis',ch:17,cn:'Gökyüzü',href:'chapter-17.html'},
  {fa:'دود',tr:'Duman',ch:17,cn:'Gökyüzü',href:'chapter-17.html'},
  {fa:'گرم',tr:'Sıcak',ch:17,cn:'Gökyüzü',href:'chapter-17.html'},
  {fa:'سرد',tr:'Soğuk',ch:17,cn:'Gökyüzü',href:'chapter-17.html'},
  {fa:'پدر',tr:'Baba',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'مادر',tr:'Anne',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'برادر',tr:'Erkek Kardeş',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'خواهر',tr:'Kız Kardeş',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'پسر',tr:'Erkek Çocuk',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'دختر',tr:'Kız',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'شوهر',tr:'Koca',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'خانم',tr:'Hanım (Eş)',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'پدر کلان',tr:'Dede',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'مادر کلان',tr:'Nine',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'نواسه',tr:'Torun',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'کاکا',tr:'Amca',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'ماما',tr:'Dayı',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'خاله',tr:'Teyze',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'عمه',tr:'Hala',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'فرزند',tr:'Evlat',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'مرد',tr:'Adam / Erkek',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'شخص / نفر',tr:'Şahıs / Kişi',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'نامزد',tr:'Nişanlı',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'داماد',tr:'Damat',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'عروس',tr:'Gelin',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'خسر',tr:'Kayınpeder',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'خوشو',tr:'Kayınvalide',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'خسر بره',tr:'Kayınbirader',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'یازنه',tr:'Enişte',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'زن برادر',tr:'Yenge',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'برادر زاده- خواهر زاده',tr:'Yeğen',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'برادر رضاعی',tr:'Süt Kardeş',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'پدر اندر',tr:'Üvey Baba',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'مادر اندر',tr:'Üvey Anne',ch:18,cn:'Akraba',href:'chapter-18.html'},
  {fa:'الله / خداوند',tr:'Allah',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'دین',tr:'Din',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'وحی',tr:'Vahiy',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'قدر / سرنوشت',tr:'Kader',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'شریعت',tr:'Şeriat',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'اعتقاد',tr:'İnanç – İtikat',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'مذهب',tr:'Mezhep',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'امت',tr:'Ümmet',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'ملت',tr:'Millet',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'پیامبر',tr:'Peygamber',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'الهام',tr:'İlham',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'صحابه',tr:'Sahabe',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'تابعین',tr:'Tabiin',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'علما',tr:'Âlimler',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'مرشد کامل',tr:'Mürşid-i Kâmil',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'ولی‌الله',tr:'Evliya (Allah Dostu)',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'نماز',tr:'Namaz',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'فرض',tr:'Farz',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'واجب',tr:'Vacip',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'سنت',tr:'Sünnet',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'مکروه',tr:'Mekruh',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'وضو',tr:'Abdest',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'غسل',tr:'Gusül',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'روزه',tr:'Oruç (ek)',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'زکات',tr:'Zekât (ek)',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'قربانی',tr:'Kurban',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'توبه کردن',tr:'Tövbe Etmek',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'تسبیح',tr:'Tespih',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'ذکر',tr:'Zikir',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'تلاوت',tr:'Tilavet',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'دعا',tr:'Dua (ek)',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'خیرات و صدقات',tr:'Hayır ve Sadaka',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'محراب',tr:'Mihrap',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'منبر',tr:'Minber',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'مناره',tr:'Minare',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'صف',tr:'Saf',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'خطبه',tr:'Hutbe',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'اذان',tr:'Ezan',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'جماعت',tr:'Cemaat',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'خانقاه',tr:'Tekke / Zikir Meclisi',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'امام',tr:'İmam',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'مؤذن',tr:'Müezzin',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'حاجی',tr:'Hacı',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'جبه',tr:'Cübbe',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'دستار',tr:'Sarık',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'کلاه',tr:'Takke',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'موزهٔ مسح',tr:'Mest',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'حلال',tr:'Helal',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'حرام',tr:'Haram',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'گناه',tr:'Günah',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'ثواب',tr:'Sevap',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'ادب',tr:'Edep / Âdab',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'اخلاق',tr:'Ahlâk',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'احترام',tr:'Saygı / Hürmet',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'صداقت',tr:'Doğruluk',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'سلام',tr:'Selam',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'مرگ',tr:'Ölüm',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'مُردن',tr:'Ölmek',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'متولد شدن',tr:'Doğmak',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'قبر / مزار',tr:'Kabir / Mezar',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'کفن',tr:'Kefen',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'جنازه',tr:'Cenaze',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'تابوت',tr:'Tabut',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'رستاخیز',tr:'Diriliş (Mahşer)',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'جنت / بهشت',tr:'Cennet',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'دوزخ / جهنم',tr:'Cehennem',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'عذاب',tr:'Azap',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'نکاح',tr:'Nikâh',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'زن',tr:'Kadın',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'اولاد',tr:'Evlat / Çocuk',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'طلاق',tr:'Boşanma',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'بنده',tr:'Kul / Bende',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'فتوا',tr:'Fetva',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'حکم',tr:'Hüküm',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'شاهد',tr:'Şahit',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'وصیت‌نامه',tr:'Vasiyetname',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'شورا',tr:'Şura',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'خلافت',tr:'Hilafet',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'شیطان',tr:'Şeytan',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'کافر',tr:'Kâfir',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'مشرک',tr:'Müşrik',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'منافق',tr:'Münafık',ch:19,cn:'Dini Terimler',href:'chapter-19.html'},
  {fa:'زیرپیراهن',tr:'Atlet',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'زیرپوش',tr:'Fanila',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'نیکر',tr:'Külot / Don',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'لباس خواب',tr:'Pijama Takımı',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'شلوارک',tr:'Şort',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'پیراهن',tr:'Gömlek',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'تی‌شرت',tr:'Tişört',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'پتلون',tr:'Pantolon',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'دامن',tr:'Etek',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'جاکت',tr:'Kazak',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'جاکت بی‌آستین',tr:'Kolsuz Kazak',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'واسکت',tr:'Yelek',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'دریشی',tr:'Takım Elbise',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'دریشی زمستانی',tr:'Kışlık Takım Elbise',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'کرتی',tr:'Ceket',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'کرتی بارانی',tr:'Yağmurluk Ceket',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'بالاپوش',tr:'Manto / Pardösü',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'روسری / چادری',tr:'Başörtüsü / Eşarp',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'شال',tr:'Şal',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'گردن‌پیچ',tr:'Atkı',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'نکتایی',tr:'Kravat',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'دستکش',tr:'Eldiven',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'کمربند',tr:'Kemer / Kayış',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'جیب',tr:'Cep',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'جیب بغلی',tr:'Yan Cep',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'چوری',tr:'Bilezik',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'گردن‌بند',tr:'Kolye',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'انگشتری',tr:'Yüzük',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'گوشواره',tr:'Küpe',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'جوراب',tr:'Çorap',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'بوت',tr:'Ayakkabı',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'کفش ورزشی',tr:'Spor Ayakkabısı',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'موزه',tr:'Çizme',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'چپلی',tr:'Terlik',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'سرپایی',tr:'Halı Terliği',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'پتو',tr:'Yorgan / Battaniye',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'جان‌پاک',tr:'Banyo Havlusu',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'پیش‌بند آشپزی',tr:'Mutfak Önlüğü',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'یخن',tr:'Yaka',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'طلا',tr:'Altın',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'نقره',tr:'Gümüş',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'مس',tr:'Bakır',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'الماس',tr:'Elmas',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'یاقوت',tr:'Yakut',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'زمرد',tr:'Zümrüt',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'عقیق',tr:'Akik Taşı',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'لاجورد',tr:'Lacivert Taşı (Lâciverd)',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'فیروزه',tr:'Firuze (Turkuaz)',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'صدف',tr:'Sedef',ch:20,cn:'Giyim',href:'chapter-20.html'},
  {fa:'کوچ',tr:'Koltuk Takımı',ch:21,cn:'Mobilya',href:'chapter-21.html'},
  {fa:'میز',tr:'Masa',ch:21,cn:'Mobilya',href:'chapter-21.html'},
  {fa:'چوکی',tr:'Sandalye',ch:21,cn:'Mobilya',href:'chapter-21.html'},
  {fa:'الماری',tr:'Dolap',ch:21,cn:'Mobilya',href:'chapter-21.html'},
  {fa:'تخت دو‌طبقه',tr:'Ranza',ch:21,cn:'Mobilya',href:'chapter-21.html'},
  {fa:'تخت دو‌طبقهٔ کودک',tr:'Çocuk Ranzası',ch:21,cn:'Mobilya',href:'chapter-21.html'},
  {fa:'گهواره',tr:'Beşik',ch:21,cn:'Mobilya',href:'chapter-21.html'},
  {fa:'قالین',tr:'Halı',ch:21,cn:'Mobilya',href:'chapter-21.html'},
  {fa:'بالشت',tr:'Yastık',ch:21,cn:'Mobilya',href:'chapter-21.html'},
  {fa:'سرمیزی',tr:'Masa Örtüsü',ch:21,cn:'Mobilya',href:'chapter-21.html'},
  {fa:'روجایی',tr:'Yatak Örtüsü',ch:21,cn:'Mobilya',href:'chapter-21.html'},
  {fa:'لحاف',tr:'Yorgan',ch:21,cn:'Mobilya',href:'chapter-21.html'},
  {fa:'کمپل',tr:'Battaniye',ch:21,cn:'Mobilya',href:'chapter-21.html'},
  {fa:'پرده',tr:'Perde',ch:21,cn:'Mobilya',href:'chapter-21.html'},
  {fa:'آینه',tr:'Ayna',ch:21,cn:'Mobilya',href:'chapter-21.html'},
  {fa:'ویدیو',tr:'Video',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'کست‌پلیر',tr:'Kasetçalar',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'تیپ',tr:'Teyp',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'سیستم صدا',tr:'Hoparlör Sistemi',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'رادیو',tr:'Radyo',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'اتو',tr:'Ütü',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'میز اتو',tr:'Ütü Masası',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'ماشین خیاطی',tr:'Dikiş Makinesi',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'یخچال',tr:'Buzdolabı',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'ساعت سرمیزی',tr:'Masa Üstü Saati',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'لامپ',tr:'Lamba',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'لمپ گازی',tr:'Gaz Lambası',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'چراغ دستی',tr:'El Feneri',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'جاروبرقی',tr:'Elektrikli Süpürge',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'ماشین لباس‌شویی',tr:'Çamaşır Makinesi',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'ماشین ظرف‌شویی',tr:'Bulaşık Makinesi',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'آب‌گرم‌کن',tr:'Su Isıtıcısı',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'کمرهٔ عکاسی',tr:'Fotoğraf Makinesi',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'گلاس',tr:'Bardak',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'چاینک',tr:'Çaydanlık',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'جگ',tr:'Sürahi',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'بشقاب',tr:'Tabak',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'کاسه',tr:'Kâse',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'قنددانی',tr:'Şekerdanlık',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'پتنوس',tr:'Tepsi',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'قاشق چای',tr:'Çay Kaşığı',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'قاشق غذاخوری',tr:'Yemek Kaşığı',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'پنجـه',tr:'Çatal',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'ملاقه',tr:'Kepçe',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'تابه',tr:'Tava',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'دیگ',tr:'Kazan',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'دیگ بخار',tr:'Düdüklü Kazan',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'نمکدان',tr:'Tuzluk',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'چلوصاف',tr:'Süzgeç',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'مرتبان',tr:'Kavanoz',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'آفتابه',tr:'İbrik',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'لگن',tr:'Leğen',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'تشت',tr:'Teşt',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'سطل',tr:'Satıl',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'منقل',tr:'Mangal',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'پکه',tr:'Vantilatör',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'آب‌پاش',tr:'Bahçe Sulama İbriği',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'بیل',tr:'Kürek',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'قیچی باغبانی',tr:'Budama Makası',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'قیچی خیاطی',tr:'Terzi Makası',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'چکش',tr:'Çekiç',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'اره',tr:'Testere',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'طناب- ریسمان',tr:'İp',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'رنده',tr:'Rende',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'جارو',tr:'Süpürge',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'دستشویی',tr:'Lavabo',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'خاکستر‌دان',tr:'Kül Tabağı',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'کوت بند',tr:'Askı',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'ماشین ریش',tr:'Sakal Makinesi',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'ژیلت / تیغ',tr:'Jilet',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'موچین',tr:'Cımbız',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'پنبهٔ گوش',tr:'Kulak Pamuğu',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'دستمال کاغذی',tr:'Peçete',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'کاغذ تشناب',tr:'Tuvalet Kağıdı',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'کف ریش',tr:'Traş Köpüğü',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'عطر',tr:'Parfüm',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'کریم',tr:'Krem',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'وازلین',tr:'Vazelin',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'برس دندان',tr:'Diş Fırçası',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'کریم دندان',tr:'Diş Macunu',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'صابون',tr:'Sabun',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'شامپو',tr:'Şampuan',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'حوله',tr:'Havlu',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'شانه',tr:'Tarak',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'مسواک',tr:'Misvak',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'لوازم آرایش',tr:'Makyaj Malzemesi',ch:22,cn:'Elektronik Ev',href:'chapter-22.html'},
  {fa:'جنراتور',tr:'Jeneratör',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'ترانس برق',tr:'Trafo',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'پایه برق',tr:'Elektrik Direği',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'واتر پمپ',tr:'Su Pompası',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'کولر',tr:'Klima',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'تلویزیون',tr:'Televizyon',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'بخاری برقی',tr:'Elektrikli Soba',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'بخاری',tr:'Soba',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'بایلر / آب‌گرم‌کن',tr:'Su Isıtıcı (Boyler)',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'زنگ',tr:'Zil',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'کمپیوتر',tr:'Bilgisayar',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'لپ‌تاپ',tr:'Laptop',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'پرنتر',tr:'Yazıcı',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'نرم‌افزار',tr:'Yazılım',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'کمره',tr:'Kamera',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'دی‌وی‌دی',tr:'DVD',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'سی‌دی',tr:'CD',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'دیجیتال',tr:'Dijital',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'موبایل',tr:'Cep Telefonu',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'تلفون',tr:'Telefon',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'مخابره',tr:'Telsiz',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'سیم‌کارت',tr:'Sim Kart',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'کریدیت',tr:'Kontör',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'شارجر',tr:'Şarj Aleti',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'ریموت',tr:'Kumanda',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'میکروفون',tr:'Mikrofon',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'ساکت',tr:'Priz',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'سویچ',tr:'Elektrik Düğmesi',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'فیوز',tr:'Şalter',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'لین / کابل',tr:'Kablo',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'باتری- بالتی',tr:'Pil-Batarya',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'پیچ‌کش تست',tr:'Kontrol Kalemi- tornavida',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'پلاس',tr:'Pense',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'برمه',tr:'Matkap',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'پیچ',tr:'Cıvata',ch:23,cn:'Elektronik Cihaz',href:'chapter-23.html'},
  {fa:'ساختمان',tr:'İnşaat',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'پروژه',tr:'Proje',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'مواد / لوازم',tr:'Malzeme',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'اپارتمان',tr:'Apartman',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'واحد / آپارتمان',tr:'Daire',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'زیرزمین',tr:'Bodrum',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'طبقه بالا',tr:'Üst Kat',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'بالکن',tr:'Balkon',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'سنگ تهداب',tr:'Temel Taşı',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'کانکریت',tr:'Beton',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'سیخ گل / گادر',tr:'İnşaat Demiri',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'خشت',tr:'Tuğla',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'سمنت',tr:'Çimento',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'چونه',tr:'Kireç',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'ریگ',tr:'Kum',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'جغل',tr:'Çakıl',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'مصاله',tr:'Harç',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'هموار',tr:'Şap',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'قالب',tr:'Kalıp',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'بام',tr:'Dam',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'سقف',tr:'Tavan',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'ناوه',tr:'Oluk',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'دودکش بخاری',tr:'Soba Bacası',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'کتاره',tr:'Korkuluk',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'خوازه',tr:'İskele',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'گل‌ماله',tr:'Mala',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'کلنگ',tr:'Kazma',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'تبر',tr:'Balta',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'مارتول',tr:'Balyoz',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'تیشه',tr:'Keser',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'میخ',tr:'Çivi',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'کراچی',tr:'El Arabası',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'آب‌ترازو',tr:'Su Terazisi',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'جالی ریگ',tr:'Kum Süzgeci',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'سطل / دوله',tr:'Kum Kovası',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'حفر کردن',tr:'Çukur Kazmak',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'پر کردن',tr:'Doldurmak',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'آستر',tr:'Astar',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'گچ',tr:'Alçı',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'کاشی',tr:'Fayans',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'زینه',tr:'Merdiven',ch:24,cn:'İnşaat',href:'chapter-24.html'},
  {fa:'قلم',tr:'Kalem',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'خودکار',tr:'Tükenmez Kalem',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'خودنویس',tr:'Dolma Kalem',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'مارکر',tr:'Tahta Kalemi',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'نوک پنسل',tr:'Kalem Ucu',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'مرکب',tr:'Mürekkep',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'خط',tr:'Yazı',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'الفبا',tr:'Alfabe',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'کاغذ',tr:'Kağıt',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'کاغذ یادداشت',tr:'Not Kağıdı',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'کتابچه',tr:'Defter',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'کتاب',tr:'Kitap',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'فرهنگ',tr:'Sözlük',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'دوسیه',tr:'Dosya',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'کاپی',tr:'Fotokopi',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'چاپ',tr:'Baskı',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'مطبعه',tr:'Matbaa',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'صحاف',tr:'Sahaf',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'پاک‌کن',tr:'Silgi',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'تخته‌پاک',tr:'Tahta Silgisi',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'پنسل‌تراش',tr:'Kalem Açacağı',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'خط‌کش',tr:'Cetvel',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'قیچی',tr:'Makas',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'استپلر',tr:'Zımba',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'سوزن استپلر',tr:'Zımba İğnesi',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'پین / سنجاق',tr:'Toplu İğne',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'چسپ',tr:'Yapışkan',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'سوراخ‌کن کاغذ',tr:'Kâğıt Delgeci',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'ورق‌گیر',tr:'Sayfa Tutacağı',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'قلم‌دانی',tr:'Kalemlik',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'بکس / بیک',tr:'Çanta',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'کتابخانه',tr:'Kitaplık',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'تخته اعلانات',tr:'Pano',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'لوحه',tr:'Levha',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'چوکات',tr:'Çerçeve',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'تخته',tr:'Tahta',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'رحله',tr:'Rahle',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'برنامه',tr:'Program',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'جنتری',tr:'Takvim',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'کارت دعوت',tr:'Davetname',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'تاپه',tr:'Damga',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'مهر',tr:'Mühür',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'بیرق',tr:'Bayrak',ch:25,cn:'Kırtasiye',href:'chapter-25.html'},
  {fa:'کچالو',tr:'Patates',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'رومی',tr:'Domates',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'پیاز',tr:'Soğan',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'چای',tr:'Çay',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'زردک',tr:'Havuç',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'بادنجان سیاه',tr:'Patlıcan',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'بادرنگ',tr:'Salatalık',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'نمک',tr:'Tuz',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'شکر',tr:'Şeker',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'سیر',tr:'Sarımsak',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'مرچ',tr:'Biber',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'مرچ سرخ',tr:'Kırmızıbiber',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'مرچ سیاه',tr:'Karabiber',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'نعنا',tr:'Nane',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'لیمو',tr:'Limon',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'پالک',tr:'Ispanak',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'بامیه',tr:'Bamya',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'لوبیا',tr:'Fasulye',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'نخود',tr:'Nohut',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'نخود سبز',tr:'Bezelye',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'سمارق',tr:'Mantar',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'گلپی',tr:'Karnabahar',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'کلم',tr:'Lahana',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'کاهو',tr:'Marul',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'جعفری',tr:'Maydanoz',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'پیازچه',tr:'Yeşil Soğan',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'مرچ دلمه',tr:'Dolmalık Biber',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'جوس – آب میوه',tr:'Meyve Suyu',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'شلغم',tr:'Şalgam Turpu',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'کدوگرد',tr:'Kış Kabağı',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'کدو',tr:'Taze Kabak',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'مرچ تازه',tr:'Yeşil Biber',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'نیشکر',tr:'Şeker Kamışı',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'مولی سفید',tr:'Turp',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'مولی سرخک',tr:'Kırmızı Turp',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'فاصولیه سبز',tr:'Yeşil Fasulye',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'لبلبو',tr:'Şeker Pancarı',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'مصاله',tr:'Baharat',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'زیره',tr:'Kimyon',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'نوشابه - مشروبات',tr:'İçecek-Meşrubat',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'انگور',tr:'Üzüm',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'سیب',tr:'Elma',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'موز',tr:'Muz',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'نارنج / مالته',tr:'Portakal',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'کینو',tr:'Mandalina',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'انار',tr:'Nar',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'خربوزه',tr:'Kavun',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'تربوز',tr:'Karpuz',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'ناک',tr:'Armut',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'آلو',tr:'Erik',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'شفتالو',tr:'Şeftali',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'زردآلو',tr:'Kayısı',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'گیلاس',tr:'Kiraz',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'آلوبالو',tr:'Vişne',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'آلوچه',tr:'Yeşil Erik',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'بهی',tr:'Ayva',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'انجیر',tr:'İncir',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'توت',tr:'Dut',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'شاه‌ توت',tr:'Kara Dut',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'امبه',tr:'Mango',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'خرما',tr:'Hurma',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'کشمش',tr:'Kuru Üzüm',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'کشمش بی‌دانه',tr:'Çekirdeksiz Kuru Üzüm',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'پسته',tr:'Fıstık',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'بادام',tr:'Badem',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'چهارمغز',tr:'Ceviz',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'ممپلی',tr:'Yer Fıstığı',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'جلغوزه',tr:'Çam Fıstığı',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'ناریل',tr:'Hindistan Cevizi',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'تخم آفتابگردان',tr:'Çekirdek (Ay çekirdeği)',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'گندم',tr:'Buğday',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'برنج',tr:'Pirinç',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'جواری',tr:'Mısır',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'نسک',tr:'Mercimek',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'جو',tr:'Arpa',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'کنجد',tr:'Susam',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'خشخاش',tr:'Haşhaş',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'نان',tr:'Ekmek',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'نان سفید',tr:'Beyaz Ekmek',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'نان گندم',tr:'Buğday Ekmeği',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'نان جو',tr:'Arpa Ekmeği',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'نان جواری',tr:'Mısır Ekmeği',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'تخم‌مرغ',tr:'Yumurta',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'یخنی',tr:'Yahni / Haşlama',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'کباب',tr:'Kebap',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'کباب بره',tr:'Kuzu Kebabı',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'کوفته',tr:'Köfte',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'منتو',tr:'Mantı',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'ماکارونی',tr:'Makarna',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'ماهی بریان',tr:'Kızarmış Balık',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'قورمهٔ سمارق',tr:'Mantar Yemeği',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'بادنجان برانی',tr:'Yoğurtlu Kızartma',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'سوپ عدس',tr:'Mercimek Çorbası',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'قیمه',tr:'Kıyma',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'گوشت قیمه',tr:'Kıyma Eti',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'ساسیج',tr:'Sucuk',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'سالاد',tr:'Salata',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'آچار',tr:'Turşu',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'ساندویچ',tr:'Sandviç',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'سرکه',tr:'Sirke',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'شیرینی',tr:'Tatlı',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'کیک',tr:'Kek',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'کیک عروسی',tr:'Pasta',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'کلچه',tr:'Kuru Pasta',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'لبنیات',tr:'Süt Ürünleri',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'قیماق',tr:'Kaymak',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'مسکه',tr:'Tereyağı',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'پنیر',tr:'Peynir',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'قروت',tr:'Kurutulmuş Yoğurt',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'چکه',tr:'Süzme Yoğurt',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'شیر',tr:'Süt',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'ماست',tr:'Yoğurt',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'دوغ',tr:'Ayran',ch:26,cn:'Yemek & Gıda',href:'chapter-26.html'},
  {fa:'گوشت گوسفند',tr:'Koyun Eti',ch:27,cn:'Et Ürünleri',href:'chapter-27.html'},
  {fa:'گوشت گاو',tr:'Dana Eti',ch:27,cn:'Et Ürünleri',href:'chapter-27.html'},
  {fa:'گوشت مرغ',tr:'Tavuk Eti',ch:27,cn:'Et Ürünleri',href:'chapter-27.html'},
  {fa:'گوشت بز',tr:'Keçi Eti',ch:27,cn:'Et Ürünleri',href:'chapter-27.html'},
  {fa:'گوشت ماهی',tr:'Balık Eti',ch:27,cn:'Et Ürünleri',href:'chapter-27.html'},
  {fa:'گوشت فیل‌مرغ',tr:'Hindi Eti',ch:27,cn:'Et Ürünleri',href:'chapter-27.html'},
  {fa:'گوشت خرگوش',tr:'Tavşan Eti',ch:27,cn:'Et Ürünleri',href:'chapter-27.html'},
  {fa:'گوشت کبک',tr:'Keklik Eti',ch:27,cn:'Et Ürünleri',href:'chapter-27.html'},
  {fa:'گوشت پرندگان',tr:'Kuş Eti',ch:27,cn:'Et Ürünleri',href:'chapter-27.html'},
  {fa:'سوسیس- ساسج',tr:'Sucuk',ch:27,cn:'Et Ürünleri',href:'chapter-27.html'},
  {fa:'گوسفند',tr:'Koyun',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'بره',tr:'Kuzu',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'بز',tr:'Keçi',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'اسب',tr:'At',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'خر',tr:'Eşek',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'قاطر',tr:'Katır',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'شتر',tr:'Deve',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'سگ',tr:'Köpek',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'پیشک',tr:'Kedi',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'مرغ',tr:'Tavuk',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'خروس',tr:'Horoz',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'جوجه مرغ',tr:'Civciv',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'قاز',tr:'Kaz',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'مرغابی',tr:'Ördek',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'شیر',tr:'Aslan',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'فیل',tr:'Fil',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'خرس',tr:'Ayı',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'آهو',tr:'Ceylan',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'شغال',tr:'Çakal',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'خرگوش',tr:'Tavşan',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'خارپشت',tr:'Kirpi',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'موش کور',tr:'Köstebek',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'شادی',tr:'Maymun',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'خوگ',tr:'Domuz',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'تمساح',tr:'Timsah',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'مار',tr:'Yılan',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'چلپاسه',tr:'Kertenkele',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'سنگ‌پشت',tr:'Kaplumbağa',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'قورباغه',tr:'Kurbağa',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'خرچنگ',tr:'Yengeç',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'مورچه',tr:'Karınca',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'ملخ',tr:'Çekirge',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'عنکبوت',tr:'Örümcek',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'شاپرک',tr:'Kelebek',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'کرم ابریشم',tr:'İpek Böceği',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'زنبور عسل',tr:'Bal Arısı',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'شپش',tr:'Bit',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'کبک',tr:'Keklik',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'لک‌لک',tr:'Leylek',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'کبوتر',tr:'Güvercin',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'گنجشک',tr:'Serçe',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'قمری',tr:'Kumru',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'بلبل',tr:'Bülbül',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'قناری',tr:'Kanarya',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'طوطی',tr:'Papağan',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'پرستو',tr:'Kırlangıç',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'طاووس',tr:'Tavus Kuşu',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'عقاب',tr:'Kartal',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'شاهین',tr:'Şahin',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'شترمرغ',tr:'Deve Kuşu',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'فیل‌مرغ',tr:'Hindi',ch:28,cn:'Hayvanlar',href:'chapter-28.html'},
  {fa:'سر',tr:'Kafa',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'مو',tr:'Saç',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'پیشانی',tr:'Alın',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'شقیقه',tr:'Şakak',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'صورت',tr:'Yüz',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'چشم',tr:'Göz',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'ابرو',tr:'Kaş',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'مردمک',tr:'Göz Bebeği',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'مژه',tr:'Kirpik',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'بینی',tr:'Burun',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'گونه',tr:'Yanak',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'چانه',tr:'Çene',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'لب',tr:'Dudak',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'دهان',tr:'Ağız',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'دندان',tr:'Diş',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'زبان',tr:'Dil',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'گلو',tr:'Boğaz',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'گوش',tr:'Kulak',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'نرمهٔ گوش',tr:'Kulak Yumuşağı',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'ریش',tr:'Sakal',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'بروت',tr:'Bıyık',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'گردن',tr:'Boyun',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'شانه',tr:'Omuz',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'سینه',tr:'Göğüs',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'شکم',tr:'Karın',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'ناف',tr:'Göbek',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'پشت',tr:'Sırt',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'کمر',tr:'Bel',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'پوست',tr:'Deri / Cilt',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'بازو',tr:'Kol',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'زیر بغل',tr:'Kol Altı',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'آرنج',tr:'Dirsek',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'دست',tr:'El',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'مچ دست',tr:'El Bileği',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'کف دست',tr:'El İçi',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'انگشت',tr:'Parmak',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'شصت',tr:'Baş Parmak',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'ناخن',tr:'Tırnak',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'زانو',tr:'Diz',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'کشکک زانو',tr:'Diz Kapağı',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'پا',tr:'Ayak',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'کف پا',tr:'Ayak Tabanı',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'انگشتان پا',tr:'Ayak Parmakları',ch:29,cn:'Dış Uzuvlar',href:'chapter-29.html'},
  {fa:'مغز',tr:'Beyin',ch:30,cn:'İç Organlar',href:'chapter-30.html'},
  {fa:'قلب',tr:'Kalp',ch:30,cn:'İç Organlar',href:'chapter-30.html'},
  {fa:'شُش',tr:'Akciğer',ch:30,cn:'İç Organlar',href:'chapter-30.html'},
  {fa:'جگر',tr:'Karaciğer',ch:30,cn:'İç Organlar',href:'chapter-30.html'},
  {fa:'معده',tr:'Mide',ch:30,cn:'İç Organlar',href:'chapter-30.html'},
  {fa:'روده',tr:'Bağırsak',ch:30,cn:'İç Organlar',href:'chapter-30.html'},
  {fa:'سپرز',tr:'Dalak',ch:30,cn:'İç Organlar',href:'chapter-30.html'},
  {fa:'گرده',tr:'Böbrek',ch:30,cn:'İç Organlar',href:'chapter-30.html'},
  {fa:'مثانه',tr:'Mesane',ch:30,cn:'İç Organlar',href:'chapter-30.html'},
  {fa:'حنجره',tr:'Gırtlak',ch:30,cn:'İç Organlar',href:'chapter-30.html'},
  {fa:'رگ',tr:'Damar',ch:30,cn:'İç Organlar',href:'chapter-30.html'},
  {fa:'خون',tr:'Kan',ch:30,cn:'İç Organlar',href:'chapter-30.html'},
  {fa:'حجره',tr:'Hücre',ch:30,cn:'İç Organlar',href:'chapter-30.html'},
  {fa:'عضله',tr:'Kas',ch:30,cn:'İç Organlar',href:'chapter-30.html'},
  {fa:'استخوان',tr:'Kemik',ch:30,cn:'İç Organlar',href:'chapter-30.html'},
  {fa:'مفصل',tr:'Mafsal / Eklem',ch:30,cn:'İç Organlar',href:'chapter-30.html'},
  {fa:'قـبـرغه',tr:'Kaburga Kemikleri',ch:30,cn:'İç Organlar',href:'chapter-30.html'},
  {fa:'مریض',tr:'Hasta',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'مریضی / مرض',tr:'Hastalık',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'بی‌حال',tr:'Halsiz',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'بی‌حالی',tr:'Halsizlik',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'خسته',tr:'Yorgun',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'خستگی',tr:'Yorgunluk',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'بی‌طاقت',tr:'Takatsiz',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'بی‌طاقتی',tr:'Takatsizlik',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'لرزیدن',tr:'Titremek',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'تب',tr:'Ateş',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'سرما خوردن',tr:'Üşütmek',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'تنگی نفس',tr:'Nefes Darlığı',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'سردرد',tr:'Baş ağrısı',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'دندان‌درد',tr:'Diş ağrısı',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'چشم‌درد',tr:'Göz ağrısı',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'معده‌درد',tr:'Mide ağrısı',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'گرده‌درد',tr:'Böbrek ağrısı',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'فشار خون',tr:'Tansiyon',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'شکر',tr:'Şeker (Diyabet)',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'کولسترول-چربی خون',tr:'Kolesterol',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'کم‌خونی',tr:'Kansızlık',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'زردی',tr:'Sarılık',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'اسهال',tr:'İshal',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'قبضیت',tr:'Kabızlık',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'دل‌بدی',tr:'Mide Bulantısı',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'زخم معده',tr:'Mide Yarası',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'سنگ گرده',tr:'Böbrek Taşı',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'زکام',tr:'Nezle',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'آبله',tr:'Çiçek Hastalığı',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'سل',tr:'Verem',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'سرطان',tr:'Kanser',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'میرگی',tr:'Sara Hastalığı',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'فلج',tr:'Felç',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'سکته قلبی',tr:'Kalp Krizi',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'سکته مغزی',tr:'Beyin Kanaması',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'امراض عصبی',tr:'Asabi Hastalıklar',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'دیوانگی',tr:'Delilik',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'لکنت زبان',tr:'Dil Tutulması (Kekemelik)',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'کوری',tr:'Körlük',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'کری',tr:'Sağırlık',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'لال',tr:'Dilsiz / Lal',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'لوچی',tr:'Şaşılık',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'معلولیت',tr:'Sakatlık',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'زخم',tr:'Yara',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'زخمی شدن',tr:'Yaralanmak',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'سوختگی',tr:'Yanıklık',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'سرفه کردن',tr:'Öksürmek',ch:31,cn:'Hastalıklar',href:'chapter-31.html'},
  {fa:'دواخانه',tr:'Eczane',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'دوا فروش / داروساز',tr:'Eczacı',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'دوا / دارو',tr:'İlaç',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'نسخه',tr:'Reçete',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'بدون نسخه',tr:'Reçetesiz',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'دوز',tr:'Doz',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'طریقه استعمال',tr:'Kullanım Talimatı',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'عوارض جانبی',tr:'Yan Etki',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'تاریخ انقضا',tr:'Son Kullanma Tarihi',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'قرص-گلی',tr:'Hap',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'شربت',tr:'Şurup',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'آمپول',tr:'İğne',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'کپسول',tr:'Kapsül',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'قطره',tr:'Damla',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'مرهم',tr:'Merhem',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'مسکن',tr:'Ağrı Kesici',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'تب‌بُر',tr:'Ateş Düşürücü',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'انتی‌بیوتیک',tr:'Antibiyotik',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'ویتامین',tr:'Vitamin',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'شربت سرفه',tr:'Öksürük Şurubu',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'دوای معده',tr:'Mide İlacı',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'دوای اسهال',tr:'İshal İlacı',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'دوای حساسیت',tr:'Alerji İlacı',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'بانداژ',tr:'Bandaj',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'گاز',tr:'Gazlı Bez',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'پنبه',tr:'Pamuk',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'الکل',tr:'Alkol',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'بتادین',tr:'Tentürdiyot',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'چسب زخم',tr:'Yara Bandı',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'تب‌سنج',tr:'Termometre',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'ماسک',tr:'Maske',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'سرم درد می‌کند.',tr:'Başım ağrıyor. →',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'دوا می‌خواهم.',tr:'ilaçistiyorum. →',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'نسخه دارم.',tr:'Reçetem var. →',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'این دوا را چطور استعمال کنم؟',tr:'Bu ilacı nasıl kullanacağım? →',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'روزی چند بار؟',tr:'Günde kaç defa? →',ch:32,cn:'Eczane',href:'chapter-32.html'},
  {fa:'خلیفه',tr:'Halife',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'امیر',tr:'Emir',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'سلطان',tr:'Sultan',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'پادشاه',tr:'Padişah',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'پادشاه / ملک',tr:'Kral',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'شاه',tr:'Şah',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'شاهزاده',tr:'Şehzade',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'صدر اعظم',tr:'Başbakan',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'وزیر',tr:'Bakan',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'معین / معاون',tr:'Yardımcı (Bakan Yard.)',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'مشاور',tr:'Müşavir',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'رئیس',tr:'Başkan',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'شاروال',tr:'Belediye Başkanı',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'والی',tr:'Vali',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'ولسوال',tr:'Kaymakam',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'آمر',tr:'Amir',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'مدیر',tr:'Müdür',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'مأمور',tr:'Memur',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'مارشال',tr:'Mareşal',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'جنرال',tr:'General',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'دگروال',tr:'Albay',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'دگرمن',tr:'Yarbay',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'افسر',tr:'Subay',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'قوماندان',tr:'Komutan',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'عسکر',tr:'Asker',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'پولیس',tr:'Polis',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'حوزه / پوسته',tr:'Karakol',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'اردو / لشکر',tr:'Ordu',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'محافظ / نگهبان',tr:'Koruma / Muhafız',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'قاضی',tr:'Hâkim',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'سارنوال',tr:'Savcı',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'حقوقدان',tr:'Hukukçu',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'وکیل مدافع',tr:'Avukat',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'کاتب / منشی',tr:'Kâtip / Yazıcı',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'پروفیسور',tr:'Profesör',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'رکتور',tr:'Rektör',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'استاد',tr:'Hoca / Öğretmen',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'شاگرد',tr:'Öğrenci / Talebe',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'فیلسوف',tr:'Filozof',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'خواجه',tr:'Hoca',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'ملا - مولوی',tr:'Molla',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'داکتر',tr:'Doktor',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'نرس',tr:'Hemşire',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'دواخانه',tr:'Eczane / Eczacı',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'انجینر / مهندس',tr:'Mühendis',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'معمار',tr:'Mimar',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'برقی',tr:'Elektrikçi',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'مستری',tr:'Tamirci',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'نجار',tr:'Marangoz',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'حلب‌ساز',tr:'Tenekeci',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'مسگر',tr:'Bakırcı',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'قفل‌ساز',tr:'Çilingir',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'ساعت‌ساز',tr:'Saatçi',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'رنگ‌مال',tr:'Boyacı',ch:33,cn:'Meslekler',href:'chapter-33.html'},
  {fa:'دهقان',tr:'Çiftçi',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'باغبان',tr:'Bağcı / Bahçıvan',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'چوپان',tr:'Çoban',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'چوب‌فروش',tr:'Oduncu',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'ماهی‌فروش',tr:'Balıkçı',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'تجارت-تجار',tr:'Tüccar / Ticaret',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'دکاندار',tr:'Dükkâncı',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'بقال',tr:'Bakkal',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'میوه‌فروش',tr:'Manav',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'قصاب',tr:'Kasap',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'نانوا',tr:'Fırıncı',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'زرگر',tr:'Kuyumcu',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'قالین‌فروش',tr:'Halıcı',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'زغال‌فروش',tr:'Kömürcü',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'قناد',tr:'Şekerci',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'لبنیات‌فروش',tr:'Süt Mamulleri Satan',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'گل‌فروش',tr:'Çiçekçi',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'دلال- جلاب',tr:'Aracı / Simsar',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'کراچی‌وان',tr:'Seyyar Satıcı',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'آشپز',tr:'Aşçı',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'گارسون',tr:'Garson',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'سلمانی',tr:'Berber',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'خیاط',tr:'Terzi',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'خشکه‌شوی',tr:'Kuru Temizlemeci',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'چای‌فروش',tr:'Çaycı',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'جوالی',tr:'Hamal',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'موچی',tr:'Ayakkabı Tamircisi',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'موتروان',tr:'Şoför',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'پیلوت - خلبان',tr:'Pilot',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'کشتی‌بان',tr:'Gemi Kaptanı',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'پوسته‌رسان',tr:'Postacı',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'خبرنگار',tr:'Gazeteci',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'نویسنده',tr:'Yazar',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'ترجمان',tr:'Tercüman',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'عکاس',tr:'Fotoğrafçı',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'هنرمند',tr:'Sanatçı / Müzisyen',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'ورزشکار',tr:'Sporcu',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'سفیر',tr:'Elçi',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'سفارت',tr:'Elçilik',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'قنسلگری',tr:'Konsolosluk',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'شاروالی',tr:'Belediye',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'ولایت',tr:'İl / Vilayet',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'ولسوالی',tr:'İlçe',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'قریه- قشلاق',tr:'Köy',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'انستیتوت طب',tr:'Tıp Enstitüsü',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'طب معالجوی',tr:'Genel Tıp',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'مکتب حربی',tr:'Askerî Lise',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'اکادمی حربی / دانشگاه حربی',tr:'Harp Okulu',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'دانشگاه تخنیکی',tr:'Teknik Üniversitesi',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'انستیتوت پولی‌تخنیک',tr:'Politeknik Üniversitesi',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'دارالمعلمین',tr:'Öğretmen Okulu',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'طب اطفال',tr:'Çocuk Hastalıkları (Pediatri)',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'تعلیم و تربیه',tr:'Eğitim Fakültesi / Öğretmenlik',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'فارمسی',tr:'Eczacılık',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'اقتصاد',tr:'İktisat',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'زراعت',tr:'Ziraat',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'علوم اجتماعی',tr:'Sosyal Bilimler',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'علوم طبیعی',tr:'Fen Bilimleri',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'شرعیات',tr:'İlahiyat',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'زمین‌شناسی',tr:'Jeoloji',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'انجینری',tr:'Mühendislik',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'حقوق و علوم سیاسی',tr:'Hukuk ve Siyaset Bilimleri',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'زبان و ادبیات',tr:'Edebiyat ve Dil Bilimleri',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'هنرهای زیبا',tr:'Güzel Sanatlar',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'وترنری',tr:'Veterinerlik',ch:34,cn:'Eğitim',href:'chapter-34.html'},
  {fa:'وزارت تحصیلات عالی',tr:'Yükseköğretim Bakanlığı',ch:35,cn:'Bakanlıklar',href:'chapter-35.html'},
  {fa:'وزارت معارف',tr:'Millî Eğitim Bakanlığı',ch:35,cn:'Bakanlıklar',href:'chapter-35.html'},
  {fa:'وزارت امور خارجه',tr:'Dışişleri Bakanlığı',ch:35,cn:'Bakanlıklar',href:'chapter-35.html'},
  {fa:'وزارت اطلاعات و فرهنگ',tr:'Kültür Bakanlığı',ch:35,cn:'Bakanlıklar',href:'chapter-35.html'},
  {fa:'وزارت مخابرات و تکنالوژی معلوماتی',tr:'İletişim Bakanlığı',ch:35,cn:'Bakanlıklar',href:'chapter-35.html'},
  {fa:'وزارت آب و برق',tr:'Su ve Elektrik Bakanlığı',ch:35,cn:'Bakanlıklar',href:'chapter-35.html'},
  {fa:'وزارت امور زنان',tr:'Kadın İşleri Bakanlığı',ch:35,cn:'Bakanlıklar',href:'chapter-35.html'},
  {fa:'وزارت شهرسازی و مسکن',tr:'İskân ve Bayındırlık Bakanlığı',ch:35,cn:'Bakanlıklar',href:'chapter-35.html'},
  {fa:'وزارت شهدا و مهاجرین',tr:'Şehitler ve Muhacirler Bakanlığı',ch:35,cn:'Bakanlıklar',href:'chapter-35.html'},
  {fa:'وزارت ترانسپورت و هوانوردی ملکی',tr:'Sivil Havacılık Bakanlığı',ch:35,cn:'Bakanlıklar',href:'chapter-35.html'},
  {fa:'وزارت معادن و پترول',tr:'Maden ve Sanayi Bakanlığı',ch:35,cn:'Bakanlıklar',href:'chapter-35.html'},
  {fa:'وزارت زراعت، آبیاری و مالداری',tr:'Tarım Bakanlığı',ch:35,cn:'Bakanlıklar',href:'chapter-35.html'},
  {fa:'وزارت صحت عامه',tr:'Sağlık Bakanlığı',ch:35,cn:'Bakanlıklar',href:'chapter-35.html'},
  {fa:'وزارت عدلیه',tr:'Adalet Bakanlığı',ch:35,cn:'Bakanlıklar',href:'chapter-35.html'},
  {fa:'وزارت مالیه',tr:'Maliye Bakanlığı',ch:35,cn:'Bakanlıklar',href:'chapter-35.html'},
  {fa:'وزارت دفاع',tr:'Savunma Bakanlığı',ch:35,cn:'Bakanlıklar',href:'chapter-35.html'},
  {fa:'وزارت امور داخله',tr:'İçişleri Bakanlığı',ch:35,cn:'Bakanlıklar',href:'chapter-35.html'},
  {fa:'وزارت صنعت و تجارت',tr:'Ticaret Bakanlığı',ch:35,cn:'Bakanlıklar',href:'chapter-35.html'},
  {fa:'وزارت حج و اوقاف',tr:'Diyanet / Din İşleri Bakanlığı',ch:35,cn:'Bakanlıklar',href:'chapter-35.html'},
];